name: webpack-build-deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack --mode=production --define-process-env-node-env=production
        echo s-w.top > ./dist/CNAME
        
    - name: Publish
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: dist
        FOLDER: dist
        CLEAR_GLOBS_FILE: "./.github/workflows/.clear-target-files"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: dist
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
